### ISSUE TITLE
Internal server error when creating an order from a form in testing mode 

### ISSUE THREAD

**Issue by somathias** [pekrau/OrderPortal#1210]
**Describe the bug**
When attempting to create an order from a form that is set as "testing", the user receives an "500 internal server error" if all fields related to "Invoice address" in their account are empty. 

**To Reproduce**
1. Have an account where all fields related to "Invoice address" are empty
2. Go to an order set to "testing" mode
3. Click on "Create order"

**Expected behavior**
If the fields really ought to be filled there should be a warning notifying the user, else the autopopulate function for the order form needs to be able to handle empty invoice addresses. 

**Short-term work-around until issue is fixed**
Make sure that at least one field of the invoice address of the user's account is non-empty, i.e. put "Sweden" as country.

**Other**
Related server logs show a KeyError with respect to "invoice_ref":

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute

    result = method(*self.path_args, **self.path_kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 3290, in wrapper

    return method(self, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/code/orderportal/order.py", line 832, in post

    saver.autopopulate()

  File "/code/orderportal/order.py", line 80, in autopopulate

    self["fields"][target] = account[source]

                             ~~~~~~~^^^^^^^^

KeyError: 'invoice_ref'
```

**Comment by pekrau** [comment]
I am away today Tuesday. I will look at this tomorrow Wednesday.
/Per K

Den tis 29 aug. 2023 08:49Sonja Mathias ***@***.***> skrev:

**Comment by pekrau** [comment]
For the next bug report, it will be good to also get information about which instance experienced the problem, and the URL of the page from which the problem operation was performed. In this case, I could figure out the issue, but sometimes the bug depends on the exact configuration of the service instance.
