### ISSUE TITLE
Orders: Make searchable by date

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#226]
Which date(s), exactly?

**Comment by ellenordevine** [comment]
T.ex. på datum för "submitted", "accepted" och "closed".

**Comment by ormestad** [comment]
Titta på denna: https://www.datatables.net/

**Comment by pekrau** [comment]
Look at search and filter function in current portal orders page. Communicate with Uppsala.

**Comment by pekrau** [comment]
Datatables interface takes care of this.
