### ISSUE TITLE
Display "submit" only if order is valid

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#26]
Validity demand specified in yaml. Check for it. Requires #24 fixed.

**Comment by ewels** [comment]
Bootstrap disabled states [work on buttons](http://getbootstrap.com/css/#buttons-disabled) too..

Also potentially of interest - there's an excellent [jQuery validation plugin](http://jqueryvalidation.org/documentation/) which can handle front end (real time) validation of form inputs. Needs a little [tweaking](http://jsfiddle.net/mapb_1990/hTPY7/7/) to get it to play nicely with bootstrap, but a quick copy and paste will usually suffice.

**Comment by pekrau** [comment]
Thanks for the tip! My plan is to do this on the server, since the submit button is available only on the order display page, not on the order edit page.

**Comment by ewels** [comment]
Ok! Server side validation is a must - this would be in addition to that presumably, but it's a fair amount of work and purely for user interface reasons.

**Comment by pekrau** [comment]
Actually, the client-side validation requires some thinking: We want the user to be able to fill in invalid values as placeholders. It must be possible to save such an order for later work, or discussion with the coordinator, but it must not be possible to submit. So client-side validation should basically be just warnings.

**Comment by ewels** [comment]
Ok - should be approached with some caution then. What kind of validation are we talking? Numbers / text / e-mail addresses / phone numbers (see the [demo](http://jqueryvalidation.org/files/demo/) for some examples and the [methods](http://jqueryvalidation.org/category/methods/) for a complete list), but more complicated validation can get complex quite quickly.

It is possible to get jQuery validation to show the warnings as the form is filled in, but not prevent form submission - see [this stackoverview post](http://stackoverflow.com/questions/20891516/allow-form-to-submit-and-post-data-when-form-is-invalid-i-e-use-validation-t).

**Comment by pekrau** [comment]
The validation will be fairly basic, I think. For example, if a particular technique has been selected, then all parameters required to define how to perform that experimental step must be given.

This is how I imagine it: client-side validation does simple things (check value types, such as integer), while server-side checks that entire subtrees of fields have appropriate values. If all subtrees are valid, then the submit button on the order display page becomes valid. Else that page shows which subtress are not yet complete, so the user can go edit those.

**Comment by ewels** [comment]
Ok - in that case it's pretty simple, just add `required` to the inputs:
```html
<input required>
```
Then if the field is not filled in, it will be highlighted as an error. You could use javascript to disable the "Submit" button whilst there are client side validation errors, but allow the "Save" button at all times.

The tricky bit of what you mention is getting server side validation to change the behaviour of the submit button on the front end as the form is filled in. I think it would be easier to rely on client side validation to change this, then have the server side validation as a backup to make sure that everything worked properly _(bouncing back to the form if it fails)_. Either that or have a two-step submission process - the form is saved and displays a second page, where there is a submit button if the form is validated. This is slightly less smooth though.

**Comment by pekrau** [comment]
I haven't managed to make clear the logic I intend:

- The "Submit" button is visible only on the order display page, **not** the edit page.
- When the user fills in the order in the edit page, basic validation of fields occur.
- When the user save from the edit page, ending up in the display page, the more complex validations, including whether an order is submittable or not, is done.

This way of working, (edit, save, then submit) is actually how it is done in the current portal, so I don't think users will have a problem with it.

**Comment by ewels** [comment]
Ah ok - yup, that's the multistep process. Kul! :)
