### ISSUE TITLE
Orders: Align order status (milestones) with requirements for statistics

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#271]
status "queued" ? See #272

Process Flow Revisited ('Sverker) suggested:

- Kö
- prepstart
- sekvensstart
- leveransdatum
- best practise analys 

Note: This may be too fine-grained, and does not necessarily fit all technologies.

Vi vill även ge feedback om QC resultat i AK, prep, sekvensering, analys. samt antal reads levererade.

**Comment by pekrau** [comment]
Decision: Remove Onhold. Do **not** add Queued. Sverker's suggestions goes into another display/page.

**Comment by ellenordevine** [comment]
Take away "on hold". 
Version 2: Processing: skilj på orderstatus och projektstatus. Endast hos Illumina kan det fungera automatiskt i nuläget: när man ställer om till open i Clarity så blir det processing här. 
(olika "status": QC, library prep, seq, dataanalys, leverans rådata)

**Comment by pekrau** [comment]
Text from Ellenor into issue #292
