### ISSUE TITLE
Import of sample information

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#3]
In addition to the file upload feature it would be good to have the possibility to import files (e.g. csv) with sample information that can directly be processed and validated by the system. 

1. This way the system can feed back warnings e.g. if the number of samples deviates from what is specified in the order.
2. Ideally, data such as sample requirements should be defined in metadata files that can be accessed by the portal and used for validation of sample data. This however is a separate issue from the order portal project but I wanted to mention it here anyway.

**Comment by pekrau** [comment]
See #298
