### ISSUE TITLE
Add "checkbox" as field type

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#309]
It would be useful to have checkbox as an alternative for simple true/false questions. You could probably just change the formatting of the boolean field type to checkbox. Default should be false/unchecked.

**Comment by pekrau** [comment]
Complicated by the conditional field feature. The current JavaScript cannot handle this. Will have to figure out a way around it. Maybe a special case in JS.

**Comment by pekrau** [comment]
Think I solved it.
