### ISSUE TITLE
Field visibility implementation

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#31]
Display fields according to restrict_read flag.

**Comment by ewels** [comment]
Bootstrap [disabled](http://getbootstrap.com/css/#forms-control-disabled) and [read-only](http://getbootstrap.com/css/#forms-control-readonly) form states may be of interest to you here.

Note that if you group the form inputs into `<fieldset>` objects, you can disable entire chunks in one go.

**Comment by pekrau** [comment]
That was an interesting point. But doesn't fieldset introduce visible stuff? I don't want that, I'm happy with rows and panels...

**Comment by ewels** [comment]
Hmm, possibly a thin grey border at the bottom? Not sure off the top of the head, not much I don't think. Usually the main visible thing is the `<legend>` included within, containing some header text. This is optional and can be left out.

**Comment by ewels** [comment]
One thing that can be said for using fieldsets is that it's _semantic_ - web nerds love to go on about this stuff, using HTML tags for what they're designed for. Main thing is that it makes the web page more accessible, in that non-standard browsers and the like know how to deal with the content. Same goes for many of the newer HTML5 tags such as `<header>` and `<footer>`, `<article>` and `<section>`.

Whether it actually makes any difference in the real world is a different point. However, if it gives shortcuts to useful behaviour (such as disabling multiple inputs simultaneously) then I'm all for it.
