### ISSUE TITLE
Adding fields to groups after field has been added

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#312]
At the moment a field can only be added to a group when it is created. It would be really useful to be able to add/move/remove fields from groups also after they have been created.

**Comment by pekrau** [comment]
This requires that the set of possible groups to move the current field to is restricted to those that are not under it (if it is a group). Allowing that could result in circular graphs = disaster.

**Comment by pekrau** [comment]
I think I have solved this. There is not a field at the top of the "field edit" page allowing changing the group for a field, which may itself be a group, so entire subtrees can be moved around.
