### ISSUE TITLE
Småfix: Number of samples (Illumina)

### ISSUE THREAD

**Issue by johannalagensjo** [pekrau/OrderPortal#328]
I Illumina-formulären så är fältet "Number of samples" en rullist där man kan välja negativt värde för antal prover. Inte en katatrof, men ser inte så snyggt ut, bättre att ha fritext.

**Comment by pekrau** [comment]
It is not better to have free text, since that would allow non-integer values. Disallowing negative values may be possible, but later, since a new parameter has to be added for a field definition. Not worth the effort right now.

**Comment by pekrau** [comment]
Skip this for now.
