### ISSUE TITLE
Kolumn med form saknas

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#330]
Såg att det redan fanns inlagt att "nod" saknas i order listan. Om det inte nämnts så tror jag det även skulle behövas en kolumn där man visar vilket formulär som har använts så man snabbt ser om det är PacBio, Illumina etc. Annars kommer det bli extremt struligt vid portalmöten när vi ska assigna projekt. 

Alltså en kolumn för "nod" och en för "form".

**Comment by pekrau** [comment]
See also #346
