### ISSUE TITLE
IUID för långt och komplicerat

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#331]
Har för mig att vi diskuterade före jul att IUID är för långt och komplicerat idag. Lite oanvändsbart på konkret administrativ nivå. 
Har för mig att vi sa att vi gillade det gamla systemet med det korta 4-siffror systemet. 
Betyder dock inte att det måste vara 4 siffror nu också, men i alla fall något kortare och enklare en den ganska långa siffer/bokstavskombination som är där just nu.

**Comment by pekrau** [comment]
This is a bug in the implementation; the mechanism is basically there.
