### ISSUE TITLE
Liten detalj - avrunda filstorlek under "files" till kb. 

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#332]
Som standard brukar man ju ange filstorlek inte i b utan i kb, blir ju ganska många siffor annars på stora filer. :-)

**Comment by pekrau** [comment]
I am unhappy about this. One of the reasons for displaying a precise value is to make it easy to spot if a file is different from some other version.

**Comment by ellenordevine** [comment]
Det kan anges på andra sätt. Att använda filstorlek är inte ett acceptabelt sätt att kontrollera fil-version på som jag ser det. Det ska framgå av t.ex. filen namn och vara ett obligatoriskt fält innuti texten i filen. Alla ska kunna skriva ut filen och fortfarande se vilken version de har framför sig.  

För gemene man är filstorleken ett ganska ointressant fält som mest säger mig hur lång tid det kommer att ta att ladda ner filen. Det finns liksom en anledning varför filstorlek brukar anges i kb och inte b.

**Comment by pekrau** [comment]
OK, I give in. Using kB = 1000 bytes.
