### ISSUE TITLE
Sökfunktion för användare

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#336]
Älskar sökfunktionen för oss administratörer!
Men kanske vissa användare behöver något liknande? Om portalen ska bli riktigt användbar även för dem? Ta man en storanvändare som Leif Andersson så har han skickat in 17 projekt förra året till oss. Ta det över 3 år och han kommer ha en lista på ca 50 projekt. Då kan det vara bra att kunna söka lite. 

Inte hög prio, kanske version 2?

**Comment by pekrau** [comment]
Yes, search should be allowed for user's orders list as well. Later.

**Comment by pekrau** [comment]
Done.
