### ISSUE TITLE
Hur blir en order "undefined"?

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#337]
Detta är lite förvirrande. Hur blir en order undefined? Finns det ens den möjligheten? Och hur får man den?

**Comment by pekrau** [comment]
När orders från den gamla portalen laddas in, och ingen info då kan hittas för lämpliga statusar, då sätts den till "undefined". Så får man antingen ignorera, eller fixa till manuellt senare.
Nya orders kommer aldrig att kunna bli "Undefined".
