### ISSUE TITLE
Möjlighet att dela upp i sektioner i formulären

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#339]
Som admin fungerar det väldigt bra att jag kan se formuläret i sektioner som jag kan öppna och stänga. Samma funktion (eller liknande) skulle behövas när man fyller i formulären. Som det är nu blir det en väldigt lång lista av frågor vilket gör att det ser värre och mer komplicerat ut än det är. Ger ett rörigt intryck. 

Ej prio 1, version 2?

**Comment by pekrau** [comment]
My interpretation of this: The top-level groups (="sections") should be hidden/shown by a button, which is by default set to "hidden". Similar to the way the order view behaves.

Technically not too difficult, I think. But I am not sure it makes it more user-friendly. Maybe we should see  what users say in testing.

**Comment by ellenordevine** [comment]
Ok med mig!
