### ISSUE TITLE
Type of sample/amount of sample

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#340]
Type of sample -> ready made library

Väljer man detta så blir frågan under om "Amount of sample" väldigt förvirrande då det inte finns något val som gäller för just ready made library. Skulle behöva något där, tex.: 
**Not applicable (ready made library)**

**Comment by ormestad** [comment]
@pekrau if "sample type" = "ready-made library" do not show "sample amount"

**Comment by pekrau** [comment]
Done, but the test must be which values to show the sample_amount field for. But that's OK.
