### ISSUE TITLE
Library type

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#341]
Valet "**don't know**" fattas.

Gäller även RNA prover och frågan under "DNA library insert size".

**Comment by ormestad** [comment]
@pekrau will add "Don't know" as option. Put it on top so it becomes default value

**Comment by pekrau** [comment]
Is this relevant for forms other than Illumina sequencing? http://ngisweden.scilifelab.se/form/51006b259f2e40b2805f0c7f9e9b889f

**Comment by pekrau** [comment]
Done for Illumina sequencing.

**Comment by pekrau** [comment]
Done.
