### ISSUE TITLE
Amount of sequencing data...

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#343]
Vi är ju inte helt överens intern om hur detta ska hanteras. Vi i uppsala skulle vilja ha det striktare, stockholm vill ha det mer fritt. Här är ett förslag: 

Idag står det som förklarande text: "Please specify the amount of data required per sample". Vad sägs om att vi istället skriver "Please specify the amount of data required per sample. Please indicate if now known. For more information about how to calculate amount of data, please visit our_ information page"_

"Information page" länkar i sin tur sedan till en informationssida på portalen (kan heta t.ex. Calculating sequencing data) där vi ger lite allmän information om hur man brukar ange data för olika typer av prover, och lite om hur man kan beräkna detta. (T.ex. coverage för WGS sequencing, million read pairs för RNA etc). 
Eftersom det skiljer sig lite hur mycket data vi anser att man kan få från olika instrument och noder så lägger man självklart in en text på den sidan också om att "please contact the project coordinator at respective node for more information about maximum amount of data and read for respective instrument".

**Comment by ellenordevine** [comment]
Please indicate if "**not**" known... :-

**Comment by ormestad** [comment]
Bra att hänvisa till en informationssida, det är ju en komplex fråga som många inte har full koll på så jag tycker att det blir trubbigt att ha det för strikt. Men om vi skriver ihop lite allmän information kring det så kanske det funkar? Oftast så är ju detta något som ändå diskuteras med användaren.

**Comment by ormestad** [comment]
@pekrau will create a new info page and add links from the fields

**Comment by pekrau** [comment]
Done.
