### ISSUE TITLE
Bredar kolumn för förklarande text i formulär

### ISSUE THREAD

**Issue by ellenordevine** [pekrau/OrderPortal#344]
OBS detta gäller när man har sparat formuläret och hamnar på översiktssidan!

Kolumnen för förklarande text är ganska small och innehåller väldigt mycket text. Det gör det irriterande luftigt när man går igenom svaren för formuläret, dvs det man har fyllt i. 
Går det att göra den förklarande texten mindre, och kolumnen bredare? Så att det inte blir så luftigt mellan varje svar?

Säg till om det är svårt att förstå vad jag menar.

**Comment by pekrau** [comment]
Har du en URL till en sida som visar problemet?

**Comment by ellenordevine** [comment]
Om jag tittar på en specifik order. Tex Johannas:
http://ngisweden.scilifelab.se/order/1377516aa5014d9cab181f43eb4b64a2
Det är ju mitten kolumnen som jag som koordinator är intresserad av, och som du ser blir den väldigt luftig, medans den förklarande texten i den högra kolumnen liksom "tar över". Den högra kolumnen är ju ganska smal och har mycket (stor) text vilket resulterar i massor med radbyten. 

Detta blir extra märkbart om man som jag ofta jobbar i "halva" fönster :-)

**Comment by pekrau** [comment]
OK, jag var oklar på om det handlade om en forms page /form/... eller en order page /order/...
Har tvingat description-kolumnen att vara 60% av tabellen. Kanske är litet för mycket?
