### ISSUE TITLE
Which statuses should be shown in the orders list?

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#347]
Currently:

- Submitted
- Accepted
- Processing
- Closed

To save space, should we remove one of these? Which one? This is easy to do, and easily reversible.

**Comment by ormestad** [comment]
I would suggest removing all dates and just showing current status. We could have a small icon next to current status where we could add a link or just hover element showing a log of the different statuses and corresponding dates. This table should look clean and not too complicated.

See also [this issue](https://github.com/pekrau/OrderPortal/issues/349) where many users have requested that our internal project names and ID should be accessible in the portal. It would be great if we had room for these in this table.

**Comment by pekrau** [comment]
This table is actually only visible to admin and staff. I haven't fixed the user's orders table to use Datatables yet, see #325. I will consider #349 in this context.

The reason for showing the status change dates is that @ellenordevine wanted to be able to search dates, and that is only possible with the current design if the dates are visible in the table.

**Comment by pekrau** [comment]
I will remove "Processing" and "Closed", and see how that works.
