### ISSUE TITLE
Uppnex project ID validation

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#348]
When a user enters a project number it is immediately checked against the list of registered Uppnex projects: https://www.uppmax.uu.se/uppnex-projects
As far as I know this has to be fetched and parsed directly from the webpage...

If the project is registered the user can confirm project title and PI to make sure they enter the right ID. This is currently done manually by bioinformaticians before data delivery.

If the project is in wrong format or not found in the list the user will be prompted to register one before order submission.

**Comment by pekrau** [comment]
This is too specialized to be implemented in source code. And any solution would be too brittle, having to rely on calling an external service. So I'd rather pass.
