### ISSUE TITLE
Fel insert size i Illumina-formuläret

### ISSUE THREAD

**Issue by johannalagensjo** [pekrau/OrderPortal#400]
I Illumina-formuläret är insert size för långa bibliotek satt till 670bp. Jag tror att detta avser insert inklusive adapters? Det borde stå (Long 550 bp) #

**Comment by pekrau** [comment]
@ormestad is this so for Stockholm?

**Comment by ormestad** [comment]
Nope. Options are (average size without adapters):

- 180bp
- 350bp
- 670bp

For TruSeq Nano on NeoPrep we also use 550bp.

**Comment by johannalagensjo** [comment]
Aha, jag förstår. I Uppsala använder vi bara standard-inserten (från manualen) för både TruSeq Nano och TruSeq PCR-free (350 bp och 550bp). Kan vi formulera detta på något snyggt sätt?

**Comment by ormestad** [comment]
Kanske så här?

-180bp (Stockholm only)
- 350bp
- 550bp
- 670bp (Stockholm only)

**Comment by johannalagensjo** [comment]
Det blir jättebra, tack! Jag förstår inte riktigt hur jag kunnat missa detta, såg det först igår när jag jobbade med Clarity-configureringar.

**Comment by pekrau** [comment]
Fixat i order form "Illumina Sequencing (mod)" som kommer att bli första versionen av produktions-formuläret. (Lugn, namnet kommer att fixa innan lansering.)
