### ISSUE TITLE
Error when logging in using order submission email link

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#403]
When following the link in the order submission email below there is an error message (see below).

---

This is to confirm that the  order 'ALASSCA' has been submitted by
simon.sundling@scilifelab.se to NGI Sweden Order Portal.

It will be reviewed by the NGI Sweden Order Portal administrators who will contact you
if further infomation is needed. When the review is done, we will send
a quote and information about sample delivery.

Go to http://ngisweden.scilifelab.se/order/7406e9e3cd3b41b5a238d5705db20467 to view the order.

If you have any questions, use support@ngisweden.se

Yours sincerely,
The NGI Sweden Order Portal administrators

---

**Error message**

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 2601, in wrapper
    return method(self, *args, **kwargs)
  File "/home/per.kraulis/orderportal/order.py", line 340, in get
    self.check_readable(order)
  File "/home/per.kraulis/orderportal/order.py", line 142, in check_readable
    raise tornado.web.HTTPError(403, reason='you may not read the order')
HTTPError: HTTP 403: you may not read the order

**Comment by ormestad** [comment]
**Correction!**
The error message appears when I try to login as the non-admin account! But it should maybe still not throw an error message.

**Comment by pekrau** [comment]
Hmm, that will be hard to change. If one logs in as non-staff, then one is logged in. Although with insufficient privileges for this particular page. Will set this as an improvement request for later versions.
