### ISSUE TITLE
Link from Markdown text in field help should open new window

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#419]
Currently, the link is followed in the same window. Not good since popup window appears.

**Comment by ormestad** [comment]
Easy fix for this:

```
<head>
    <base target="_blank">
</head>
```

**Comment by pekrau** [comment]
I will have to try this!

**Comment by ormestad** [comment]
However, this will affect all links which might not be preferable...

**Comment by pekrau** [comment]
Hmm, no, this is too imperialistic. Not a useful solution.

**Comment by ormestad** [comment]
Olga means the link in the description text "Use Markdown if you want fancy display of this text data."
This link should be easy to edit.

**Comment by pekrau** [comment]
Aha. Will do, but won't deploy until maybe later today.
