### ISSUE TITLE
Is the link to a reference genome going to be used?

### ISSUE THREAD

**Issue by b97pla** [pekrau/OrderPortal#422]
In the illumina form, the user can specify a link to a reference genome for mapping. From SNP&SEQ, we don't need that link. Do Sthlm need it?

**Comment by pekrau** [comment]
@ormestad ?

**Comment by ormestad** [comment]
No we do not need this one, I think this might be only for UGC and in that case we can remove it from the Illumina form

**Comment by pekrau** [comment]
Done.
