### ISSUE TITLE
Remove "Markdown" help text for some text inputs

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#425]
@ellenordevine : Det enda som jag tycker vi kan ta bort är denna text som ligger under adresserna:
“Use Markdown if you want fancy display of this text data”
(Eller är detta redan gjort?)
Är super på projektbeskrivningen, men på adresser känns det lite onödigt och skapar mest förvirring tycker jag.

**Comment by pekrau** [comment]
All fields with type "text" will allow Markdown, so will get this help info. One could imagine disallowing Markdown when defining the field.

**Comment by ormestad** [comment]
Shouldn't the address field be `string` instead of `text`? `text` will be shown as `<textarea>` but I think it makes more sense to use single line text (`<input type="text">`).

**Comment by pekrau** [comment]
@ormestad you are right. That is how it should be done in this case. I will make another issue saying so.
