### ISSUE TITLE
The fields "Primary contact person" should default to PI? Why required?

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#442]
Love Dalén: I’m guessing that if information about “primary contact person” is left blank, then this is assumed to be the PI? If so, this should be stated in the info text below the fields where name and contact info is given. [...] I see now that the order in fact cannot be submitted when there are missing values. This is very irritating, when for example the PI is the same person as the “primary contact”. Perhaps you can instead make some fields “non-required”?

Me: It looks like these fields are required. Is that a good idea? Should they not be allowed to be blank, in which case the PI is assumed?

@ormestad @ellenordevine : What do you think?

**Comment by ormestad** [comment]
We could make it optional and add "(if left blank it is assumed the PI is primary contact person)".
Should we do the same with BX responsible?

**Comment by pekrau** [comment]
Done.
