### ISSUE TITLE
Please add options for de-novo projects

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#443]
Love Dalén: It would be good with options for de-novo projects (ordering various mate-pair sizes), or alternatively there should be a “don’t know” option so that one can specify the request for various mate-pair libraries in the “project description”.

@ormestad @ellenordevine What do you think?

**Comment by ormestad** [comment]
But we have that. When choosing mate-pair there is a conditional field where you can choose mate-pair size.

Currently the first option is [none] so maybe we should change that to "Do not know"?

**Comment by pekrau** [comment]
OK, I will leave this without action.
