### ISSUE TITLE
Add field for grant ref number?

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#447]
Love Dalén: Shouldn’t you have a field where the grant reference number can be filled in (i.e. the VR dnr)?

But do we need this? Or is it good to have, just in case?

**Comment by ormestad** [comment]
We already have that in the current portal but we don't use it in LIMS. We haven't needed it so far so I think we can skip it.

**Comment by pekrau** [comment]
We skip this. No need to require info if we are not going to use it.
