### ISSUE TITLE
Allow specifying multiple funders

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#448]
Love Dalén: It would also be useful if several funders could be added (quite often, a project is funded by several different funding agencies).

**Comment by ormestad** [comment]
Not sure if we want to deal with that... Currently we have a drop down list in LIMS for funding and if we want more than one we probably need to add additional UDF's.

If the portal could generate a comma separated string of several funders chosen from a list of **pre-set** values it could work. In that case we can just copy/paste this whole string into a free text LIMS field.
When using this for statistics we do not want to deal with free text entered by the user, this must be a pre populated list of funders...

**Comment by pekrau** [comment]
Multiselect field allows this.
