### ISSUE TITLE
Allow project status updates from LIMS

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#47]
Users with a lot of project have commented on that it would be good to see which orders are open, finished and so on. In the current portal we do have the possibility to change that but this is not used since its to complicated to maintain. 

It would be great if the status could be automatically updated based on open/queue/close date in LIMS.

**Comment by pekrau** [comment]
Define API for these actions.
An external script must do the actual work, fetching info from LIMS and setting the order status in OrderPortal.
