### ISSUE TITLE
Fix format for news section

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#473]
Should be the same as in the "Events" section.

- Add class `nobr` to date column, remove class `text-right small`
- Remove brackets around date
- Move date column in front of main text

```
<tr>
<th class="nobr">2016-04-26</th>
<td>
<strong>TITLE</strong>
<p>TEXT</p>
</td>
</tr>
```

**Comment by pekrau** [comment]
Actually just did it. See #472
