### ISSUE TITLE
Formatting of order view

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#474]
The [table](http://ngisweden.scilifelab.se/order/NGI00050) where the filled in values are viewed could use some formatting to be clearer.

Fore example like this:

```
<tr>
<th>
    Principal Investigator name
    <p class="small">(If you are creating this order on behalf of a PI, please give the name of that PI.)</p>
</th>

<td>
    Mattias
</td>

<td>
    <span data-toggle="tooltip" title="Valid value." class="text-success">
        <span class="glyphicon glyphicon-ok"></span>
    </span>
</td>
</tr>
```

I think there is a class called small in Bootstrap (added to the `p` element in the title).
I think this change will make the table clearer and gives more space to the relevant values added to the order.

**Comment by pekrau** [comment]
This is complicated by the Python Markdown library. That description is processed by it, and it appears some CSS stuff (classes?) are set by it. Trying to use p with class "small" changes nothing.

**Comment by pekrau** [comment]
Wrong. My test was screwed up.
