### ISSUE TITLE
Organizing orders in discrete logical steps

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#5]
To make the order process easier and feel less daunting it would be nice to divide it into discrete steps that is filled in and finished one by one before going on to the next. This could be configurable by grouping fields into categories in the order template. For example:

1. Sign up / Login
2. Add / review contact information (shipping/invoice address, email, phone number, invoice reference, additional contacts etc). It should be made clear that one account should only have ONE invoice address, if a lab for some reason use more than one invoice address they must create two separate accounts. This information should be saved between orders and normally only reviewed for each new order.
3. Basic order information (title, funding, ethics permits etc)
4. Sample information and library preparation
5. Sequencing
6. Bioinformatic analysis and data delivery
7. Review and submit order (can also summarize warnings about required fields, validation errors etc). Would be nice to add a "I need help" feature that generates a Zendesk ticket with a direct link to the order for users who don't know how to complete it.

**Comment by pekrau** [comment]
An order is organized hierarchically according to how the fields in the form are organized. This partly addresses the above request.

It does not prescribe a specific "workflow" for how the user should fill in things. But the field/order validity checks will make it impossible to submit an order that is incomplete.
