### ISSUE TITLE
Re-arrangement of order admin section

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#523]
It would be useful for us coordinators if the contents of the `Admin`
 section of an order instead was shown for example inside of the box with status and history.

I understand this might not be easy to do since that section is just a custom part of the form. An alternative would be to alway have it expanded so we don't have to click it to see the assigned node and admin comments.

**Comment by pekrau** [comment]
Letting it be expanded by default may be fairly simple to add.

**Comment by pekrau** [comment]
Should have responded to this long ago: It is possible to set a group field to be expanded by default:

When creating or editing the group field, check the box marked "Initial display". This can be done also for forms that are enabled.
