### ISSUE TITLE
Order of order statuses wrong in order history :P

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#536]
The order of the  different statuses in the order history is a bit strange...

![image](https://cloud.githubusercontent.com/assets/2486519/16258453/4e8687ca-385e-11e6-88a7-56730e77e8fe.png)

**Comment by pekrau** [comment]
It sorts according to date (datetime is not stored for this), and if the date is the same, the order for those becomes random. Not sure how to fix that.

**Comment by pekrau** [comment]
Fixed.
