### ISSUE TITLE
Check Clarity LIMS logic for 'aborted'

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#541]
For the NGI Stockholm update script `load_clarity_projects_info.py`. There are apparently a number of projects with 'aborted' **and** closed. What gives?

Currently, the 'aborted' status is ignored by the above script.

Check this with @ormestad when he is back.

**Comment by ormestad** [comment]
`closed` is a hardcoded LIMS field while the `aborted`field is a UDF, so if a project is aborted it still needs to be closed in order to be removed from the ones listed as "in progress".

**Comment by pekrau** [comment]
OK, so that means that an `aborted` project really is aborted? When I did the first run of the LIMS fetch script, it seemed to me that too many projects were `aborted`, so I commented out that part.

So, given what you say, I should simply add that code back, since an `aborted` status can be assumed to be correct.

**Comment by ormestad** [comment]
`aborted`==Aborted :)

**Comment by pekrau** [comment]
Haha! :+1:
