### ISSUE TITLE
Collapse the navbar for mobile phones

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#55]

**Comment by ewels** [comment]
If you use the bootstrap navbar, this is done for you automatically: http://getbootstrap.com/components/#navbar

**Comment by pekrau** [comment]
But I thought one had to define something for the navbar to make it behave so? Will look at it.

**Comment by ewels** [comment]
If you copy the markup from their example, you should be fine.

This chunk is the show/hide button (only shown on mobile):
```html
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
```

The navbar contents are handled by the `navbar-collapse collapse` classes:
```html
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
```
