### ISSUE TITLE
Use jquery UI datepicker for date input

### ISSUE THREAD

**Issue by pekrau** [pekrau/OrderPortal#66]

**Comment by ewels** [comment]
There's a bootstrap-specific datepicker which works really well with the bootstrap theme and doesn't depend on jQuery UI: https://github.com/eternicode/bootstrap-datepicker

(see the [sandbox](http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox) and [docs](https://bootstrap-datepicker.readthedocs.org/en/latest/))

**Comment by pekrau** [comment]
No need for date input, actually.
