### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by ormestad** [pekrau/OrderPortal#689]
Earlier this year the NGI project ID and name were added as tags for orders, but this seems to have stopped working (roughly since after summer....).

This is something which is useful for both the users and NGI staff so it would be great if it could be fixed. Not sure if it's a bug or if it has been changed intentionally.

**Comment by ormestad** [comment]
Mail from Love Dalén below:

---

Hello,

Here is som unsolicited user feed-back for you regarding the NGI Portal ;)

Since around May, it seems that the project IDs (e.g. L.Dalen_17_28) are no longer shown under the column “tags” in the order portal. It would be extremely helpful for us users if this information was given here, since it makes it much easier to keep track of which project is which.

Other things, although I realize this might be more compicated to fix, would be the possibility to export the “My Orders” tanel in excel format, and to have all emails regarding a specific project somehow linked to the NG Portal (i.e. that one can access the NGI Portal, go to a particular project and there see all the email correspondence linked to that project).

Cheers,

Love

**Comment by pekrau** [comment]
Mattias, jag tror detta är ett problem på NGI-sidan. Jag har mig veterligen inte ändrat något, så jag skulle tro att det skript som dunkar in detta i OrderPortal har slutat fungera av någon anledning. Det här görs alltså enligt push (ett script hos NGI laddar in det i OrderPortal), **inte** pull (OrderPortal hämtar inte detta fårn NGI).

Kanske har pwd eller API-nyckeln för kontot ändrats? Ni måste jaga tag i error-loggen för det skriptet, kanske i cron?

**Comment by pekrau** [comment]
Fixat.
