### ISSUE TITLE
Stricter email validation for orders

### ISSUE THREAD

**Issue by remiolsen** [pekrau/OrderPortal#695]
The form validation for `bioinformatics_email`, `pi_email` and `lab_emails` seems to be a bit lax. I have seen users enter variations of:

* `a.person@university.se; b.person@university.se`
* `a.person@university.se; b.pers`
* `A. Person <a.person@university.se>`

How about implementing something like this: https://stackoverflow.com/a/46181

**Comment by pekrau** [comment]
The problem here is that there is no specific field type "email" to enable this constraint on. The input field is just a one-line string. So a solution requires creating a field type "email" **and** changing those fields in the affected forms to use that new field type.

**Comment by pekrau** [comment]
I am implementing this as yet another field type. There is no JS-based error check (none such are used in this system), rather the usual on-save error checking mechanism is used: If invalid email value, then the order cannot be submitted.

**Comment by pekrau** [comment]
Implemented and deployed. As I wrote before, one needs to make a new form (clone and edit) in order to delete the old email fields and replace them by the new ones using the type 'email'. You should let @ormestad  or some other coordinator do that.
